[package]
name = "volumio-remote"
version = "1.2.0"
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png"] }
ksni = { version = "0.3", default-features = false, features = ["blocking", "tokio"] }
serde_json = "1.0.151"
slint = { version = "1.18.1", default-features = false, features = ["std", "backend-winit", "backend-winit-x11", "renderer-software", "software-renderer-systemfonts", "compat-1-2"] }
tokio = { version = "1.53.2", default-features = false, features = ["rt", "sync", "time", "macros"] }
ureq = "3.4.2"
zbus = { version = "5.19.0", default-features = false, features = ["tokio"] }

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
